In [4]:
from sklearn.linear_model import LinearRegression
#house size
X=[[1000],[1200],[1500],[1800]]
#house price (in lakh)
y=[40,50,65,80]
model=LinearRegression()
model.fit(X,y)
prediction=model.predict([[1600]])
print("prediction price",prediction[0],"lakh")

prediction price 70.0 lakh


In [8]:
from sklearn.cluster import KMeans
import numpy as np
data=np.array([[2,3],[3,4],[10,12],[11,13]])
model=KMeans(n_clusters=2,random_state=42)
model.fit(data)
print("Cluster Labels:")
print(model.labels_)

Cluster Labels:
[0 0 1 1]


In [13]:
from sklearn.cluster import KMeans
import numpy as np
data=np.array([[2,3],[3,4],[10,12],[11,13]])
model=KMeans(n_clusters=1,random_state=42)
model.fit(data)
print("Cluster Labels:")
print(model.labels_)

Cluster Labels:
[0 0 0 0]


In [11]:
from sklearn.cluster import KMeans
import numpy as np
data=np.array([[2,3],[3,4],[10,12],[11,13]])
model=KMeans(n_clusters=4,random_state=42)
model.fit(data)
print("Cluster Labels:")
print(model.labels_)

Cluster Labels:
[2 0 3 1]


In [14]:
from sklearn.linear_model import LinearRegression
x=([1],[2],[3],[4],[5],[6],[7])
y=[12.5,8.2,15.0,10.4,7.0,9.3,6.8]
model=LinearRegression()
model.fit(x,y)
prediction=model.predict([[8]])
print("Predicted Rainfall for Day 8:", round(prediction[0], 2), "mm")

Predicted Rainfall for Day 8: 6.61 mm
