In [1]:
pip install numpy

mambajs 0.21.4

Process pip requirements ...

Requirement numpy already handled by conda/micromamba/mamba.


In [2]:
import numpy as np

In [2]:
import numpy as np
a=np.array(["sneha","sanvi","saloni","sakshi"])
print(a)

['sneha' 'sanvi' 'saloni' 'sakshi']


In [3]:
a=np.array(["pineapple","orange","mango","apple"])
print(a)

['pineapple' 'orange' 'mango' 'apple']


In [4]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
a=np.ones((2,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
b=a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
a=np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
b=a.reshape(4,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
a=np.array([[1,2],[3,4]])
print(a.flatten())

[1 2 3 4]


In [18]:
a=np.array([[[1,2,3],[4,5,9],[4,6,8]]])
print(a.flatten())

[1 2 3 4 5 9 4 6 8]


In [19]:
a=np.array([10,30,40,222,192])
print(a[0])

10


In [21]:
a=np.array([10,20,40,33,43,50,35])
a.sort()
print(a)

[10 20 33 35 40 43 50]


In [20]:
a=np.array([10,20,40,33,43,50,35])
a.sort()
print(a[5])

43


In [23]:
a=np.array([10,20,40,33,43,50,35])
a.sort()
print(a[-2])

43


In [24]:
a=np.array([10,20,40,33,43,50,35])
a.sort()
print(a[-3])

40


In [27]:
a=np.array([[[1,2,3],[4,5,9],[4,6,8]]])
print(a[0,1])

[4 5 9]


In [13]:
a=np.array([[[1,2,3],[4,5,9],[4,6,8]]])
print(a[0,2])
print(np.sort(a))

[4 6 8]
[[[1 2 3]
  [4 5 9]
  [4 6 8]]]


In [36]:
a=np.array([[[1,2,4],[3,6,44],[3,9,8]]])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)
print(a.flatten())
print(type(a))
b=a.reshape(3,3)
print(b)

[[[ 1  2  4]
  [ 3  6 44]
  [ 3  9  8]]]
3
int32
(1, 3, 3)
9
[ 1  2  4  3  6 44  3  9  8]
<class 'numpy.ndarray'>
[[ 1  2  4]
 [ 3  6 44]
 [ 3  9  8]]


In [12]:
a=np.array([10,20,30,22,32,44,41])
print(np.sort(a))
print(a[-2])

[10 20 22 30 32 41 44]
44


In [39]:
a=np.array([[[1,2,4,9],[3,6,44,3],[3,9,8,5]]])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)
print(a.flatten())
print(type(a))
b=a.reshape(4,3)
print(b)

[[[ 1  2  4  9]
  [ 3  6 44  3]
  [ 3  9  8  5]]]
3
int32
(1, 3, 4)
12
[ 1  2  4  9  3  6 44  3  3  9  8  5]
<class 'numpy.ndarray'>
[[ 1  2  4]
 [ 9  3  6]
 [44  3  3]
 [ 9  8  5]]


In [46]:
a=np.array([[[1,2,4,9],[3,6,44,3],[3,9,8,5]]])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)
print(a.flatten())
print(type(a))
b=a.reshape(4,3)
print(b)

print(a[0,2])

[[[ 1  2  4  9]
  [ 3  6 44  3]
  [ 3  9  8  5]]]
3
int32
(1, 3, 4)
12
[ 1  2  4  9  3  6 44  3  3  9  8  5]
<class 'numpy.ndarray'>
[[ 1  2  4]
 [ 9  3  6]
 [44  3  3]
 [ 9  8  5]]
[3 9 8 5]


In [47]:
a=np.array([[[1,2,3,4],[3,4,5,6],[3,6,8,4]]])
print(a.flatten())

[1 2 3 4 3 4 5 6 3 6 8 4]


In [48]:
a=np.array([[[1,2,3,4],[3,4,5,6],[3,6,8,4]]])
print(a.reshape(4,3))

[[1 2 3]
 [4 3 4]
 [5 6 3]
 [6 8 4]]


In [59]:
a=np.array([[[1,2,4,9],[3,6,44,3],[3,9,8,5]]])
print(a)
print(a[0][1][1])

[[[ 1  2  4  9]
  [ 3  6 44  3]
  [ 3  9  8  5]]]
6


In [65]:
a=np.array([[[1,2,4,9],[3,6,44,3],[3,9,8,5]]])
print(a[0,2,2])

8


In [63]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[1][1])

4


In [54]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [66]:
a=int(input("enter a number"))
b=int(input("enter a number"))
print("addition=",a+b)
print("subtraction=",a-b)
print("multiplication=",a*b)
print("division=",a/b)
print("remainder=",a%b)

enter a number 30
enter a number 20


addition= 50
subtraction= 10
multiplication= 600
division= 1.5
remainder= 10


In [68]:
a=np.array([10,20,30,40])
print(a[1:4])

[20 30 40]


In [69]:
a=np.array([10,11,12,13,14])
b=np.array([2,2,3,3,4,])
print(a+b)

[12 13 15 16 18]


In [70]:
a=np.array([10,11,12,13,14])
b=np.array([2,2,3,3,4,])
print(a-b)

[ 8  9  9 10 10]


In [71]:
a=np.array([10,11,12,13,14])
b=np.array([2,2,3,3,4,])
print(a*b)

[20 22 36 39 56]


In [72]:
a=np.array([10,11,12,13,14])
b=np.array([2,2,3,3,4,])
print(a**b)

[  100   121  1728  2197 38416]


In [75]:
a=np.array([100,102,103,104,105])
b=np.array([1,2,2,3,3])
print(a+b)
print(a-b)
print(a*b)
print(a**2)

[101 104 105 107 108]
[ 99 100 101 101 102]
[100 204 206 312 315]
[10000 10404 10609 10816 11025]


In [76]:
a=np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [78]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [87]:
a=np.random.randint(1,100)
print(a)

72


In [88]:
a=np.random.randint(1,100,size=3)
print(a)

[67 18 14]


In [89]:
a=np.random.randint(1,100,size=12)
print(a)

[31 66  7 59 95 41 61 70 84 71 54 36]


In [2]:
import numpy as np
a=np.random.randint(1,100,12)
print(a)

[51 11 83 96 52 35  7 79 61 80 31 37]


In [32]:
a=np.random.randint(1,100,(3,4))
print(a)

[[51 28 30 22]
 [84 26 52 83]
 [68  2 61 87]]


In [91]:
a=np.array([2,30,50,55,60])
b=a[a>50]
print(b)

[55 60]


In [3]:
pip install numpy

mambajs 0.21.4

Process pip requirements ...

Requirement numpy already handled by conda/micromamba/mamba.


In [4]:
import numpy as np

In [5]:
a=np.array([1,30,5,8,9])
print(np.sqrt(a))

[1.         5.47722558 2.23606798 2.82842712 3.        ]


In [6]:
a=np.array([2,3,5,6,9])
print(np.abs(a))

[2 3 5 6 9]


In [7]:
a=np.array([2.3,3.6,5.7,6.8,9])
print(np.abs(a))

[2.3 3.6 5.7 6.8 9. ]


In [8]:
a=np.array([2.3,3.6,5.7,6.8,9])
print(np.exp(a))

[   9.97418245   36.59823444  298.86740097  897.84729165 8103.08392758]


In [9]:
a=np.array([2,3,5,6,9])
print(np.exp(a))

[7.38905610e+00 2.00855369e+01 1.48413159e+02 4.03428793e+02
 8.10308393e+03]


In [10]:
a=np.array([2,3,5,6,9])
print(np.log(a))

[0.69314718 1.09861229 1.60943791 1.79175947 2.19722458]


In [11]:
a=np.array([2,3,5,6,9])
print(np.sin(a))

[ 0.90929743  0.14112001 -0.95892427 -0.2794155   0.41211849]


In [15]:
a=np.array([90])
print(np.sin(a))

[0.89399666]


In [12]:
a=np.array([2,3,5,6,9])
print(np.cos(a))

[-0.41614684 -0.9899925   0.28366219  0.96017029 -0.91113026]


In [13]:
a=np.array([2,3,5,6,9])
print(np.tan(a))

[-2.18503986 -0.14254654 -3.38051501 -0.29100619 -0.45231566]


In [14]:
a=np.array([0])
print(np.tan(a))

[0.]


In [17]:
a=np.array([1,4,25,36,49,100])
print(np.sqrt(a))

[ 1.  2.  5.  6.  7. 10.]


In [18]:
a=np.array([1,4,25,36,49,100])
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.abs(a))

[ 1.  2.  5.  6.  7. 10.]
[2.71828183e+00 5.45981500e+01 7.20048993e+10 4.31123155e+15
 1.90734657e+21 2.68811714e+43]
[0.         1.38629436 3.21887582 3.58351894 3.8918203  4.60517019]
[  1   4  25  36  49 100]


In [20]:
a=np.array([[[1,2,3,99],[4,5,6,7],[6,7,9,66]]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
print(type(a))
print(a.flatten())
print(a.reshape(4,3))
print(a[0,1,1])

[[[ 1  2  3 99]
  [ 4  5  6  7]
  [ 6  7  9 66]]]
(1, 3, 4)
12
3
int32
<class 'numpy.ndarray'>
[ 1  2  3 99  4  5  6  7  6  7  9 66]
[[ 1  2  3]
 [99  4  5]
 [ 6  7  6]
 [ 7  9 66]]
5


In [21]:
a=np.array([10,20,30,40,33])
b=a.copy()
b[0]=100
print(a)
print(b)

[10 20 30 40 33]
[100  20  30  40  33]


In [22]:
a=np.array([10,20,30,40,33])
b=a.view()
b[0]=100
print(a)
print(b)

[100  20  30  40  33]
[100  20  30  40  33]


In [24]:
a=np.array([10,20,44,60,44])
print(np.random.randint(1,100,20))


[ 7 51 62 61 90 85 65  9  4 92 95 25 12 60 59 57 93 31 57  8]


In [30]:
a=np.array([10,20,44,60,44])
print(np.random.randint(1,100,(3,2)))


[[64 21]
 [61 83]
 [67 93]]


In [26]:
a=np.array([10,20,30,40,50])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))


30.0
30.0
14.142135623730951
50
10


In [29]:
a=np.array([10,20,30,40,50])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))
print(np.sum(a))
print(np.sort(a)[2])


30.0
30.0
14.142135623730951
50
10
150
30


In [33]:
a=np.array([10,33,77,88,34,55])
print("average",np.mean(a))
print("highest",np.max(a))
print("lowest",np.min(a))

average 49.5
highest 88
lowest 10


In [3]:
pip install numpy


mambajs 0.21.4

Process pip requirements ...

Requirement numpy already handled by conda/micromamba/mamba.


In [4]:
import numpy as np

In [3]:
pip install numpy

mambajs 0.21.4

Process pip requirements ...

Requirement numpy already handled by conda/micromamba/mamba.


In [4]:
import numpy as np

In [6]:
a=np.array([2500,38400,4849,4759,3849,7490,36758,20398,4747,2948,3849,2849,7499,233,45,48498,3848,38489,378,48998,38499,3849,48949,4759,8499])
print("highest",np.max(a))

highest 48998


In [8]:
a=np.array([2500,38400,4849,4759,3849,7490,36758,20398,4747,2948,3849,2849,7499,233,45,48498,3848,38489,378,48998,38499,3849,48949,4759,8499])
print("highest",np.max(a))
print("lowest",np.min(a))
print(np.mean(a))
print(np.sort(a))
print(np.median(a))
print(np.std(a))


highest 48998
lowest 45
15437.56
[   45   233   378  2500  2849  2948  3848  3849  3849  3849  4747  4759
  4759  4849  7490  7499  8499 20398 36758 38400 38489 38499 48498 48949
 48998]
4759.0
17612.146392941435


In [8]:
a=np.array([2500,38400,4849,4759,3849,7490,36758,20398,4747,2948,3849,2849,7499,233,45,48498,3848,38489,378,48998,38499,3849,48949,4759,8499])
print("highest",np.max(a))
print("lowest",np.min(a))
print(np.mean(a))
print(np.sort(a))
print(np.median(a))
print(np.std(a))


highest 48998
lowest 45
15437.56
[   45   233   378  2500  2849  2948  3848  3849  3849  3849  4747  4759
  4759  4849  7490  7499  8499 20398 36758 38400 38489 38499 48498 48949
 48998]
4759.0
17612.146392941435


In [ ]:
RollNo,Name,Math,Science,English,Computer,SocialStudies
101,Alice,88,91,85,90,87
102,Bob,76,82,79,85,80
103,Charlie,92,89,94,91,90
104,David,68,74,70,72,75
105,Emma,95,97,96,98,94
106,Frank,81,78,84,80,79
107,Grace,89,92,90,93,91
108,Hannah,73,69,75,77,74
109,Ian,84,86,82,88,85
110,Julia,91,9

0,93,95,92

In [11]:
import numpy as np
a=np.array([10,20,30,33,22,41,34,11])
print(a)
print(a.shape)
print(a.size)
print(a.dtype)
print(type(a))
print(a.ndim)
print(a.reshape(4,2))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.sort(a))
print(np.sort(a)[::-1])


[10 20 30 33 22 41 34 11]
(8,)
8
int32
<class 'numpy.ndarray'>
1
[[10 20]
 [30 33]
 [22 41]
 [34 11]]
41
10
25.125
[10 11 20 22 30 33 34 41]
[41 34 33 30 22 20 11 10]


In [10]:
import numpy as np
a=np.array([10,20,30,33,22,41,34,11])
print(a)
print(a.shape)
print(a.size)
print(a.dtype)
print(type(a))
print(a.ndim)
print(a.reshape(4,2))
print(np.max(a))
print(np.min(a))
print(np.mean(a))


[10 20 30 33 22 41 34 11]
(8,)
8
int32
<class 'numpy.ndarray'>
1
[[10 20]
 [30 33]
 [22 41]
 [34 11]]
41
10
25.125


In [3]:
a=np.empty((2,2))
print(a)

[[2.22393310e-307 1.76094754e-307]
 [2.20051673e-287             nan]]


In [7]:
a=np.array([12,20,30,22,11,9,8])
b=a.copy()
b[0]=100
print(a)
print(b)

[12 20 30 22 11  9  8]
[100  20  30  22  11   9   8]


In [8]:
a=np.array([10,29,38,930,89,90,78])
b=a.view()
b[1]=20
print(a)
print(b)

[ 10  20  38 930  89  90  78]
[ 10  20  38 930  89  90  78]


In [17]:
a=np.array([10,20,30,40,50,55,60,66])
b=np.array([1,1,2,2,3,3,4,4])
print(a+b)
print(a*b)
print(a/b)
print(a-b)
print(a**2)

[11 21 32 42 53 58 64 70]
[ 10  20  60  80 150 165 240 264]
[10.         20.         15.         20.         16.66666667 18.33333333
 15.         16.5       ]
[ 9 19 28 38 47 52 56 62]
[ 100  400  900 1600 2500 3025 3600 4356]


In [20]:
a=([10,12,13,15,33,44,55,43,24,29,31])
print(np.sort(a))

[10 12 13 15 24 29 31 33 43 44 55]


In [21]:
a=np.empty((4))
print(a)

[4.24399158e-313 8.48798317e-313 1.16709769e-312 1.40051722e-312]


In [24]:
a=np.linspace(1,20)
print(a)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


In [27]:
a=np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [2]:
import numpy as np
a=np.array([10,20,30,40,12,33,44,50,60,88,89,90,101,105,120])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
print(type(a))
print(a.reshape(3,5))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.sqrt(a))
print(np.abs(a))

[ 10  20  30  40  12  33  44  50  60  88  89  90 101 105 120]
(15,)
15
1
int32
<class 'numpy.ndarray'>
[[ 10  20  30  40  12]
 [ 33  44  50  60  88]
 [ 89  90 101 105 120]]
120
10
59.46666666666667
50.0
35.22852379661812
[2.30258509 2.99573227 3.40119738 3.68887945 2.48490665 3.49650756
 3.78418963 3.91202301 4.09434456 4.47733681 4.48863637 4.49980967
 4.61512052 4.65396035 4.78749174]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 1.62754791e+05 2.14643580e+14 1.28516001e+19 5.18470553e+21
 1.14200739e+26 1.65163625e+38 4.48961282e+38 1.22040329e+39
 7.30705998e+43 3.98951957e+45 1.30418088e+52]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.53657292  0.99991186
  0.01770193 -0.26237485 -0.30481062  0.0353983   0.86006941  0.89399666
  0.45202579 -0.97053528  0.58061118]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.84385396 -0.01327675
  0.99984331  0.96496603 -0.95241298  0.99937328  0.51017704 -0.44807362
  0.89200487 -0.24095905  0.81418097]
[ 6.48360827

In [7]:
import numpy as np
a=np.array([[10,20,30],[40,20,90],[28,39,22],[39,29,23],[20,38,77]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
print(type(a))
print(a.reshape(3,5))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.sqrt(a))
print(np.abs(a))

[[10 20 30]
 [40 20 90]
 [28 39 22]
 [39 29 23]
 [20 38 77]]
(5, 3)
15
2
int32
<class 'numpy.ndarray'>
[[10 20 30 40 20]
 [90 28 39 22 39]
 [29 23 20 38 77]]
90
10
35.0
29.0
20.94118748622755
[[2.30258509 2.99573227 3.40119738]
 [3.68887945 2.99573227 4.49980967]
 [3.33220451 3.66356165 3.09104245]
 [3.66356165 3.36729583 3.13549422]
 [2.99573227 3.63758616 4.34380542]]
[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 4.85165195e+08 1.22040329e+39]
 [1.44625706e+12 8.65934004e+16 3.58491285e+09]
 [8.65934004e+16 3.93133430e+12 9.74480345e+09]
 [4.85165195e+08 3.18559318e+16 2.75851345e+33]]
[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316  0.91294525  0.89399666]
 [ 0.27090579  0.96379539 -0.00885131]
 [ 0.96379539 -0.66363388 -0.8462204 ]
 [ 0.91294525  0.29636858  0.99952016]]
[[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.40808206 -0.44807362]
 [-0.96260587  0.26664293 -0.99996083]
 [ 0.26664293 -0.74805753 -0.53283302]
 [ 0.40808206  0.95507364 -0.03097

In [4]:
print(np.sort(a))

[ 10  12  20  30  33  40  44  50  60  88  89  90 101 105 120]


In [6]:
print(np.sort(a)[::-1])

[120 105 101  90  89  88  60  50  44  40  33  30  20  12  10]


In [4]:
import numpy as np
a=np.array([[[[1,2,3,4],[5,5,6,7],[3,4,8,9],[20,30,40,5]]]])
print(a.shape)

(1, 1, 4, 4)


In [5]:
print(a.size)

16


In [7]:
print(np.max(a))
print(np.min(a))

40
1
